version: "3.9"

services:
  logging-service:
    container_name: face-recognition-logging-service
    build: ./logging_service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8004/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      cassandra-ddl:
        condition: service_completed_successfully
    networks:
      - face-recognition-network
    ports:
      - "8004:8004"

  cassandra-node-1:
    container_name: face-recognition-cassandra-node-1
    image: "cassandra:latest"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    networks:
      - face-recognition-network

  cassandra-ddl:
    container_name: face-recognition-cassandra-ddl
    image: "cassandra:latest"
    depends_on:
      cassandra-node-1:
        condition: service_healthy
    volumes:
      - ./logging_service/ddl.cql:/ddl.cql
    command: /bin/bash -c "cqlsh cassandra-node-1 -f /ddl.cql"
    networks:
      - face-recognition-network

  analytics-service:
    container_name: face-recognition-analytics-service
    build: ./analytics_service
    depends_on:
      logging-service:
        condition: service_healthy
    networks:
      - face-recognition-network
    ports:
      - "8005:8005"

networks:
  face-recognition-network:
    name: face-recognition-network
