# Test your FastAPI endpoints

GET http://127.0.0.1:8005/alltime_stats
Accept: application/json

###

GET http://127.0.0.1:8005/daily_stats
Accept: application/json


###
GET http://127.0.0.1:8004/appearances_by_location/office
Accept: application/json
